### ISSUE TITLE
hyper.nonExportable is not working for attributes

### ISSUE THREAD

**Issue by Sorix** [SyncDB/SYNCPropertyMapper#123]
It seems that `hyper.nonExportable` works only for relationships, so it can't be used for attributes. If you have added that key to whole framework it maybe very unclear that it works only for relationships.

Anyway that key will be very useful for attributes, e.g. if you don't want to export some secrets or binary data.

I don't know if it is expected behavior or bug, so I've posted example project with bug reproduction.

XCode project: [hypbug_nonExportable.zip](https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/files/499500/hypbug_nonExportable.zip)

**Versions:**
  - NSManagedObject-HYPPropertyMapper (4.1.1):
    - DateParser (~> 0.1.0)
    - NSEntityDescription-SYNCPrimaryKey (~> 1.2.6)

**Related:**
* PR #113 (source)
* PR #120 (readme)
* Issue #112

**Comment by 3lvis** [comment]
Hi @Sorix!

I only implemented it for relationships but I see how it could be useful for attributes as well.

Nice suggestion. 👍

**Comment by 3lvis** [comment]
# Available on [5.0.1](https://github.com/SyncDB/SYNCPropertyMapper/releases/tag/5.0.1) 💥
