### ISSUE TITLE
[Feature Request] hyp_dictionary only for changedValues

### ISSUE THREAD

**Issue by RolandasRazma** [SyncDB/SYNCPropertyMapper#126]
It would be good to have only changed values. 

Pseudocode:

``` swift
extension NSManagedObject {
    func hyp_dictionary( changesOnly: Bool = false ) -> [String : Any] {
        var json = self.hyp_dictionary(using: .array)

        if changesOnly {
            let changed = [String](self.changedValues().keys).map({ (key: String) -> String in
                return key.hyp_remote()
            })

            for (key, _) in json {
                if changed.contains(key) == false {
                    json.removeValue(forKey: key)
                }
            }
        }

        return json
    }
}
```

there is bug in this implementation - it doesn't handle relationships and custom keys.

I guess correct place for such change would be in 
`-[NSManagedObject hyp_dictionaryWithDateFormatter:parent:usingRelationshipType:]`

Best change would be to add "forLocalKeys:" in `-[NSManagedObject hyp_dictionaryWithDateFormatter:parent:usingRelationshipType:]` instead of "only changed"

`-[NSManagedObject hyp_dictionaryWithDateFormatter:parent:usingRelationshipType:forLocalKeys:]` that way you can pass changedKeys or whatever keys you interested in

**Comment by 3lvis** [comment]
@RolandasRazma How does it know what changed, though? 

Also, can you provide some use cases?

**Comment by RolandasRazma** [comment]
@3lvis There is method -[NSManagedObject changedValues] that returns changed keys/values.

Use case: change to server only changes (PATCH) instead of whole object

**Comment by 3lvis** [comment]
@RolandasRazma that's only useful before you save, once you save it probably doesn't work, right?

**Comment by RolandasRazma** [comment]
@3lvis right. Whats why I guess its better to add 2 new methods
-[NSManagedObject hyp_dictionaryWithDateFormatter:parent:usingRelationshipType:forLocalKeys:]
and
-[NSManagedObject hyp_dictionaryWithDateFormatter:parent:usingRelationshipType:forRemoteKeys:]

**Comment by RolandasRazma** [comment]
actually just realised you don't need second method as you can just filter

**Comment by 3lvis** [comment]
Ohhh, I see.

I'm more for just keeping the simple solution that solves most of the cases than adding something that might make the codebase harder to maintain.

If there's something that really should be excluded you can always use the `hyper.nonExportable` attribute.

More info here:
https://github.com/SyncDB/NSManagedObject-HYPPropertyMapper/blob/master/README.md#excluding

What do you think? Would you personally prefer to keep the source and APIs clean? Or the tradeoff is so valuable than you would include this?

**Comment by RolandasRazma** [comment]
hi, `hyper.nonExportable` is not the same, but you right about code complexity. I guess its your choice in the end. Feel free to close issues.

Attaching patch just in case

[patch.diff.zip](https://github.com/SyncDB/NSManagedObject-HYPPropertyMapper/files/513422/patch.diff.zip)

**Comment by 3lvis** [comment]
I was mainly checking on how critical this is for you. Very critical, or nice to have?

**Comment by RolandasRazma** [comment]
Nothing is critical :) I cal always workaround it or simply fork/patch

**Comment by 3lvis** [comment]
Closing this for now since the adding this functionality makes the codebase slightly more complex and adds logic when the original method is enough for most cases.

Please just comment in this issue if this is needed for you as well. Let's reconsider if there are more requests.
