### ISSUE TITLE
JSON / Attribute Mapping Trouble

### ISSUE THREAD

**Issue by padlocked17** [SyncDB/SYNCPropertyMapper#129]
I have been working on getting Sync up and running and I've run into several issues I'm trying to sort through.  The first one involves attribute mapping with the JSON I've got below:

```json
[
    {
        "id": 2312,
        "date": "2005-05-15T13:02:20",
        "custom_meta": {
            "edit_lock": [
                "1402941716:3"
            ],
            "edit_last": [
                "3"
            ]
        }
    }
]
```

I've added "hyper.remoteKey : custom_meta.edit_last" to the User Info fields on my CoreData attribute in order to attempt and grab that value, but I'm thinking the fact the value is enclosed in an array is causing me to not be able to grab that data.  Am I overlooking something?

**Comment by marthinfreij** [comment]
Key paths doesn't work on arrays/collections. I haven't tried it, but Collection Operators might work.

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/CollectionOperators.html#//apple_ref/doc/uid/20002176-BAJEAIEE

**Comment by 3lvis** [comment]
@padlocked17 This is correct, the mapping that you're applying works for dictionaries. Does your arrays always have one item?

**Comment by padlocked17** [comment]
@marthinfreij I will look into the Collection Operators and see if that might do the trick.

@3lvis 9 out of 10 times it will hold a single value.  There are exceptions on certain fields where the "custom_meta" dictionary  would contain an array of dictionaries to serve up some data.  Do you have suggestions for either scenario?

**Comment by padlocked17** [comment]
Unless I'm missing something, Collection Operators don't appear to provide a solution.  Throwing "custom_meta.edit_last[0]" into the hyper.RemoteKey doesn't seem to pull it either.  Any ideas on how I could map into that array and grab the values?

**Comment by 3lvis** [comment]
@padlocked17 maybe you would like to consider to either pre-process your JSON so it takes a value from the array and makes it a dictionary instead or you could also store your array as NSData then in your app you could deserialize it.

**Comment by marthinfreij** [comment]
@padlocked17 using @min or @max to aggregate the array to a single value might work in this case, but it's a really ugly solution. keyPaths don't support subscripting, so pre-processing is probably the best way forward.

**Comment by 3lvis** [comment]
@padlocked17 This should be a good workaround for your issue.

https://github.com/SyncDB/SYNCPropertyMapper#dealing-with-bad-apis

**Comment by padlocked17** [comment]
Do you have any examples of the usage of this in conjunction with the Sync framework?  Being that the JSON is simply passed into the "changes" function, I'm not sure where I would actually utilize this at.  I've got the transformer class built and the Core data attribute added, but I'm not sure how to incorporate the `ValueTransformer.setValueTransformer(BadAPIValueTransformer(), forName: NSValueTransformerName(rawValue: "BadAPIValueTransformer"))` before the `hyp_fill(with:)`.

Any guidance or prodding you can give?

**Comment by 3lvis** [comment]
Hi @padlocked17, just put the `setValueTransformer` call before calling `Sync.changes`. That should work. Let me know otherwise :)
