### ISSUE TITLE
hyp_dictionary combine case and type for related attributes

### ISSUE THREAD

**Issue by achirkof** [SyncDB/SYNCPropertyMapper#140]
It would be great to combine several attributes, for example `case` for entities and `type` for relation in one expression
```swift
let entityJSON = entity.hyp_dictionary(.camelCase)
let entityJSON = entity.hyp_dictionary(using: .array)
```
to
```swift
let entityJSON = entity.hyp_dictionary(attributes: [RelationType: .array, CaseType: .camelCase])
```

**Comment by 3lvis** [comment]
Looks like there are a few issues https://github.com/SyncDB/SYNCPropertyMapper/pull/141#issuecomment-261780325

**Comment by 3lvis** [comment]
The mapping for to-many relationships was always snakeCase.
