### ISSUE TITLE
Locale aware NSNumberFormatter 

### ISSUE THREAD

**Issue by zenangst** [SyncDB/SYNCPropertyMapper#39]
https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/b1430dbc9e96d177cad6d1d9016bdd1069ed949c/Source/NSManagedObject%2BHYPPropertyMapper.m#L118

**Comment by 3lvis** [comment]
This problem is related to using `,` and `.` when parsing strings as numbers. PropertyMapper should be smart enough to understand both.

**Comment by 3lvis** [comment]
This is still an issue. I'm going to close it since it's just a convenience, we don't officially support parsing strings as numbers.
