### ISSUE TITLE
Description attribute remote prefix confusion on entity name with two words

### ISSUE THREAD

**Issue by markosankovic** [SyncDB/SYNCPropertyMapper#87]
Hi Elvis,

From the documentation:

> Reserved attributes should be prefixed with the entityName (type becomes userType, description becomes userDescription and so on).

What if we have entity with name such as WeatherAlert. I would assume that description attribute is then weatherAlertDescription. Unfortunately, this is not the case - the mapping doesn't work. I realized that I'm making a mistake just after looking at the source code [here](https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/master/Source/NSManagedObject%2BHYPPropertyMapperHelpers.m#L142).  For now I am using weatheralertDescription as attribute name.

**Comment by 3lvis** [comment]
@markosankovic this sucks! Thanks a lot for reporting it. I'll look into it. :heart:

**Comment by 3lvis** [comment]
Should be working fine.
