### ISSUE TITLE
Possible issue caused by using lowercase string

### ISSUE THREAD

**Issue by 3lvis** [SyncDB/SYNCPropertyMapper#93]
Could be related to https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/87

```
- (NSString *)remotePrefix {
    return [NSString stringWithFormat:@"%@_", [self.entity.name lowercaseString]];
}
```

**Comment by cflorion** [comment]
My app crashes systematically on that line.

I am trying to export my core data objects to json. But after looping for a while my app crashes on that line.

I have just started using HYPPropertyMapper and I have a question: Is is a drop-in solution ? I mean it seams that it is doing an infinite loop. Is this possible ? 

Thanks :)

**Comment by 3lvis** [comment]
@cflorion Hi! Would you mind sharing your Core Data model? I would have a look :)

**Comment by cflorion** [comment]
Of course! Is it possible via email ? :)

**Comment by cflorion** [comment]
Anyway, here it is https://www.dropbox.com/s/01xijc5pdbjii17/Datamodel.xcdatamodel.zip?dl=1
Could you tell me once you've downloaded it so I can remove it please ? Thanks a lot! ;)

**Comment by 3lvis** [comment]
Removed!

**Comment by 3lvis** [comment]
@cflorion That's easily the biggest core data model I've ever seen. Are you having problems with an specific entity? (or relationship?)

**Comment by cflorion** [comment]
Hi @3lvis 
Thanks for a quick reply ;)
I know, the data model is quite big...
When i use HYPPropertyMapperRelationshipTypeNested or HYPPropertyMapperRelationshipTypeArray I get a crash, but no crash with HYPPropertyMapperRelationshipTypeNone.

I am trying to figure out where the problem could come from.
As a first step I put an NSLog in the file "NSManagedObject+HYPPropertyMapper", in the for loop of the method called

````
- (NSDictionary *)hyp_dictionaryWithDateFormatter:(NSDateFormatter *)dateFormatter parent:(NSManagedObject *)parent usingRelationshipType:(HYPPropertyMapperRelationshipType)relationshipType {
````

I get this kind of output: 
````
ItemOrder • clientID
ItemOrder • colourIndex
ItemOrder • comment
ItemOrder • creationDat
ItemOrder • deletedMotif
ItemOrder • indexInSection
ItemOrder • isPaid
ItemOrder • macroCategory
ItemOrder • name
ItemOrder • quantity
````

With this I print the last property read before the crash. But depending of which object I print, the last property read differs, so I don't think this had to do with the property itself.

Another thing, when I call .hyp_dictionary on a managed object, it takes ages to do it (before it crashes). From what I see it seems that it also goes up the entire objects graph tree. 

For example he tree can be like like this Account > Restaurant > Till > Order > ItemOrder > OptionOrder.

If I print an order for example, I would like all its itemOrders with their optionOrders, but not the till.
Is there a way to filter inverseRelationships ?

Thanks ;)

**Comment by 3lvis** [comment]
Should be working fine, tried on master and everything is fine.
